# This is the modloader configuration for fix-railway
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/example/fix-railway/issues"

[[mods]]
modId="fixrailway"
version="0.1.0"
displayName="Fix Railway"
description='''
A mod to enhance railway systems in Minecraft.
Adds new railway blocks, items, and functionality.
'''
authors="YourName"
credits="Special thanks to the Minecraft modding community."

[[dependencies.fixrailway]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fixrailway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"